class Program
{
    static void Main()
    {
        EventClass obj1 = new EventClass("Object 1");
        EventClass obj2 = new EventClass("Object 2");

        HandlerClass handler = new HandlerClass();

        obj1.Event += handler.HandleEvent;

        obj2.Event += handler.HandleEvent;

        obj1.TriggerEvent();
        obj2.TriggerEvent();
    }
}
class EventClass
{
    public delegate void EventHandler(string name);
    public event EventHandler Event;

    private string name;

    public EventClass(string name)
    {
        this.name = name;
    }

    public void TriggerEvent()
    {
        Event?.Invoke(name);
    }
}

class HandlerClass
{
    public void HandleEvent(string name)
    {
        Console.WriteLine($"Event generated by {name}");
    }
}